version: "3.9"
services:
  api-server:
    image: "api-server"
    ports:
      - "127.0.0.1:9004:9004"
    environment:
      API_SERVER_HTTP_PORT: "9004"
      API_SERVER_SERVICE_MANAGER_URL: "http://service-manager:9001"
      API_SERVER_SLEEP: "5"
    depends_on:
      - "ceresdb"
      - "service-manager"
    tty: true
  asset-manager:
    image: "asset-manager"
    ports:
      - "127.0.0.1:9002:9002"
    environment:
      ASSET_MANAGER_DB_USERNAME: "ceresdb"
      ASSET_MANAGER_DB_PASSWORD: "ceresdb"
      ASSET_MANAGER_DB_HOST: "ceresdb"
      ASSET_MANAGER_DB_NAME: "velocimodel"
      ASSET_MANAGER_DATA_PATH: "/home/asset-manager/data/assets"
      ASSET_MANAGER_DB_PORT: "7437"
      ASSET_MANAGER_HTTP_PORT: "9002"
      ASSET_MANGER_API_SERVER_URL: "http://api-server:9004"
      ASSET_MANAGER_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  ceresdb:
    image: "ceresdb"
    ports:
      - "127.0.0.1:7437:7437"
    environment:
      CERESDB_LOG_LEVEL: "info"
  frontend:
    image: "frontend"
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      FRONTEND_HTTP_PORT: "9000"
      FRONTEND_API_SERVER_URL: "http://api-server:9004"
      FRONTEND_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  model-manager:
    image: "model-manager"
    ports:
      - "127.0.0.1:9003:9003"
    environment:
      MODEL_MANAGER_DB_USERNAME: "ceresdb"
      MODEL_MANAGER_DB_PASSWORD: "ceresdb"
      MODEL_MANAGER_DB_HOST: "ceresdb"
      MODEL_MANAGER_DB_NAME: "velocimodel"
      MODEL_MANAGER_DB_PORT: "7437"
      MODEL_MANAGER_HTTP_PORT: "9003"
      MODEL_MANGER_API_SERVER_URL: "http://api-server:9004"
      MODEL_MANAGER_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  service-manager:
    image: "service-manager"
    ports:
      - "127.0.0.1:9001:9001"
    environment:
      SERVICE_MANAGER_DB_USERNAME: "ceresdb"
      SERVICE_MANAGER_DB_PASSWORD: "ceresdb"
      SERVICE_MANAGER_DB_HOST: "ceresdb"
      SERVICE_MANAGER_DB_NAME: "velocimodel"
      SERVICE_MANAGER_PARAMS_PATH: "/home/service-manager/data/config.json"
      SERVICE_MANAGER_SECRETS_PATH: "/home/service-manager/data/secrets.json"
      SERVICE_MANAGER_DB_PORT: "7437"
      SERVICE_MANAGER_HTTP_PORT: "9001"
      SERVICE_MANAGER_ENCRYPTION_KEY: "abcdefghijklmnopqrstuvqxyz012345"
      SERVICE_MANAGER_SLEEP: "5"
    depends_on:
      - "ceresdb"
    tty: true
