version: "3.9"
services:
  api-server:
    image: "api-server"
    ports:
      - "127.0.0.1:9004:9004"
    environment:
      API_SERVER_SLEEP: "5"
    depends_on:
      - "ceresdb"
      - "service-manager"
    tty: true
  asset-manager:
    image: "asset-manager"
    ports:
      - "127.0.0.1:9002:9002"
    environment:
      ASSET_MANAGER_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  auth-manager:
    image: "auth-manager"
    ports:
      - "127.0.0.1:9005:9005"
    environment:
      AUTH_MANAGER_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  ceresdb:
    image: "ceresdb"
    ports:
      - "127.0.0.1:7437:7437"
    environment:
      CERESDB_LOG_LEVEL: "info"
  frontend:
    image: "frontend"
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      FRONTEND_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  model-manager:
    image: "model-manager"
    ports:
      - "127.0.0.1:9003:9003"
    environment:
      MODEL_MANAGER_SLEEP: "5"
    depends_on:
      - "api-server"
    tty: true
  service-manager:
    image: "service-manager"
    ports:
      - "127.0.0.1:9001:9001"
    environment:
      SERVICE_MANAGER_SLEEP: "5"
    depends_on:
      - "ceresdb"
    tty: true
